#Specify the running environment
language: go
#Specify go version, you can specify multiple
node_js:
  - 1.9.2

#Run the script command
script:
  - go run main.go

#Specify the branch. The script will only be run when the specified branch is submitted.
branches:
  only:
    - main